### ISSUE TITLE
[bug] default state value isn't applied when using `.create_with`

### ISSUE THREAD

**Issue by samandmoore** [Betterment/steady_state#5]
**Context:**
Sometimes, it is useful to create new records using the `.find_or_create_by` method.

Relatedly, but not necessary to demonstrate the issue, when using `.find_or_create_by`, it's common to use the `.create_with` method in a chain to specify other attributes to provide when creating an unfound record that aren't part of the `.find_by` matching criteria.

**An example:**
`Material.find_or_create_by(id: 123)`

When doing this, with `steady_state`, the library does not populate the default value. If you have a not-null constraint on your state/status column then you get an error, same with a presence validation.

**Expected behavior:**
The create fork of the `find_or_create_by` populates the state/status column with the default value.

Here's a full class and usage:
```ruby
ActiveRecord::Schema.define do
  create_table "materials", force: :cascade do |t|
    t.string "state", null: false
  end
end

class Material < ActiveRecord::Base
  include SteadyState

  steady_state :state do
    state 'solid', default: true
    state 'liquid', from: 'solid'
    state 'gas', from: 'liquid'
    state 'plasma', from: 'gas'
  end
end

Material.find_or_create_by(id: 123)
```

Thanks for making this wonderful library. I don't have time to fix this right now, but I'm happy to help in a few weeks.

**Comment by samandmoore** [comment]
psych! this does work, i was just including `SteadyState` incorrectly 🤦‍♂️

**Comment by smudge** [comment]
no worries! there _is_ a known issue where default column values (like, in the schema) interfere with steady state's default state management. something to keep in mind. maybe i'll make a note to self about adding that to the docs.
