### ISSUE TITLE
Syntactic Sugar for accessing list of attribute enum values easily

### ISSUE THREAD

**Issue by agirlnamedsophia** [Betterment/steady_state#9]
I would like to propose adding a pluralized class method that exposes quickly the list of available attributes as defined through `steady_states`'s `enum` associated with the chosen field (the attribute or column). I know you can access this list via `ChosenClass.state_machines[:attribute].states` but I feel like folks might enjoy the added simplicity.

Eg in this class, `Material.states` would return `['solid', 'liquid', 'gas', 'plasma']`
```
class Material < ApplicationRecord
  include SteadyState

  steady_state :state do
    state 'solid', default: true
    state 'liquid', from: 'solid'
    state 'gas', from: 'liquid'
    state 'plasma', from: 'gas'
  end
end
```

and this would expose `Meal.courses` as `['breakfast', 'elevenses', 'dinner', 'supper']`
```
class Meal < ApplicationRecord
  include SteadyState

  steady_state :course do
    state 'breakfast', default: true
    state 'elevenses', from: 'breakfast'
    state 'dinner', from: 'elevenses'
    state 'supper', from: 'dinner'
  end
end
```

**Comment by smudge** [comment]
This is a great idea! Would love to ship a new release with this -- are you implementing it as I type? 😄 

I have a couple addtional ideas to throw out there on how the API could work:

1. An escape hatch? Similar to disabling auto-scope methods with `scopes: false` (to avoid method conflicts).

```ruby
def self.courses
  # my own custom definition of the method
end

steady_state :course, states_getter: false do
  # ...
end
```

2. I think it might make sense to the values with `SteadyState::Attribute::State`. It would effectively do this (but there's probably a cleaner way of writing this in a place where more constants/values are available in scope):

```ruby
ChosenClass.state_machines[:attribute].states.map do |state|
  SteadyState::Attribute::State.new(ChosenClass.state_machines[:attribute], state, nil)
end
```

The `State` decorator is mostly just additional syntactic sugar on top of a stringy value (the will still act like strings), but it makes it an "inquiry" string (so you can do `state.elevenses?` and get `true` or `false`) and adds `may_become?`, `next_values`, and `previous_values` so you can ask the state object about traversal rules.

It might even make sense to make the `StateMachine#states` method do that wrapping -- I'm not sure what the implications would be for the other parts of the state machine internals.
